title: Wenqi Xu's Homepage
page-top-title: Wenqi Xu
top-section-bg-text: Cultural Industry Management
home-subtitle: Wenqi Xu&ensp;|&ensp;徐文琪
copyright-text: '&copy; Wenqi Xu 2021-2025. All Rights Reserved.'
